name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest -v
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=E203,W503
    - name: Check code style with Black
      run: |
        black -l 80 --check roentgen test roentgen.py
    - name: Test render
      run: |
        roentgen render -b 10.000,20.000,10.001,20.001 --cache test/data
    - name: Test icon generation
      run: |
        roentgen icons
    - name: Test MapCSS 0.2 generation
      run: |
        roentgen mapcss
    - name: Test element generation
      run: |
        roentgen element --node amenity=bench,material=wood
    - name: Test tile generation
      run: |
        roentgen tile --coordinates 46.09498,10.06879 --cache test/data
