name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v
    - name: Render test
      run: |
        python roentgen.py render -b 37.415,55.753,37.416,55.754 --cache test/data
    - name: Icon generation test
      run: |
        python roentgen.py icons
    - name: MapCSS 0.2 generation test
      run: |
        python roentgen.py mapcss
