name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 black
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=E203,W503
    - name: Check code style with Black
      run: |
        black -l 80 --check roentgen test roentgen.py
    - name: Test render
      run: |
        python roentgen.py render -b 37.415,55.753,37.416,55.754 --cache test/data
    - name: Test icon generation
      run: |
        python roentgen.py icons
    - name: Test MapCSS 0.2 generation
      run: |
        python roentgen.py mapcss
    - name: Test element generation
      run: |
        python roentgen.py element --node amenity=bench,material=wood
